### DISCUSSION TITLE
No setup or config entry setup function defined

### DISCUSSION THREAD

**Discussion by espont** [amaximus/met_alerts_hu#14] [General]
Szia, nagyon szeretném használni a bővítményedet, de ezt a hibát kapom a log-ban, bármit teszek: 

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 21:59:28 (1 occurrences)
Last logged: 21:59:28
Setup failed for custom integration met_alerts_hu: No setup or config entry setup function defined.

Ez a configuration.yaml:
met_alerts_hu:
  platform: met_alerts_hu
  name: 'MET alerts'
  region_id: 1105
  county_id: 11

HA: core-2022.4.6
supervisor-2022.04.0
met_alerts_hu: 4015c97 on Dec 10 2021

Köszönöm ha segítesz!

**Comment by amaximus** [comment]
Szia,

a következőt kell beírnod a configuration.yaml-ba:
```
sensor:
  - platform: met_alerts_hu
    name: 'MET alerts'
    region_id: 1105
    county_id: 11
```
majd újra kell indítani a HA-t
