### ISSUE TITLE
Sensor not recognised

### ISSUE THREAD

**Issue by nagyv** [amaximus/met_alerts_hu#17]
Hi,

I can't get `met_alerts_hu` working.

What I did:

1. I installed `met_alerts_hu` using HACS
2. Defined in `configuration.yaml`

```yaml
sensor:
  - platform: met_alerts_hu
    name: 'Időjárás figyelmeztetések'
    region_id: 1307 # Gödöllői körzet
    county_id: 13 # Pest county
    lang: hu
```
3. Restarted Home assistant

- I can't find `sensor.met_alerts_hu` under "Entities" or "Developer Tools / States".
- The logs don't show any error
- I checked and the `met_alerts_hu` code is available under `custom_components/met_alerts_hu`. 

What setup step do I miss?
