### ISSUE TITLE
Alerts not correct

### ISSUE THREAD

**Issue by nagyrobi** [amaximus/met_alerts_hu#5]
My config:
```
- platform: met_alerts_hu
  name: 'Meteorológiai riasztás'
  region_id: 101
```

Component state (fresh restart of HA, updated at _18:54_):
```
alerts:
  - level: '1'
    type: Zivatar
    icon: mdi:weather-lightning-rainy
  - level: '2'
    type: Hőség
    icon: mdi:weather-sunny-alert
dominant_met_alert_value: 2
dominant_met_alert: Hőség
updated: '2021-06-21 18:54 '
nr_of_alerts: '2'
provider: Data provided by met.hu
friendly_name: Meteorológiai riasztás
icon: mdi:weather-sunny-alert
```
Actual (current) alerts state on met.hu page, in the same time show that there are no alerts for region 101, since _18:37_:
![kép](https://user-images.githubusercontent.com/1550668/122802928-451fc680-d2c6-11eb-9847-a2c4b6813eba.png)

**Comment by nagyrobi** [comment]
Seems like the component is not looking at the actual alerts but at the probable alert forecasts for _today_. 
This is a bit confusing.

**Comment by amaximus** [comment]
As per below description there are alert per region and sort of alerts per county:

https://www.met.hu/idojaras/veszelyjelzes/omsz_veszelyjelzo_rendszere/

**Comment by nagyrobi** [comment]
That part is OK, I'm talking about
a) current state:
![kép](https://user-images.githubusercontent.com/1550668/122830307-73ae9900-d2e8-11eb-9307-2a0312db10fd.png)

b) forecast for today (=monday):
![kép](https://user-images.githubusercontent.com/1550668/122830404-93de5800-d2e8-11eb-817c-1261beb387fb.png)

c) forecast for tomorrow (=tuesday):
![kép](https://user-images.githubusercontent.com/1550668/122830461-a789be80-d2e8-11eb-89b5-18bc9330a9c3.png)

d) and so on for 2 more days.

The component is errorneously pulling data for b) while it should pull data for a).

**Comment by nagyrobi** [comment]
Thinking it over a little bit it could contain all the information...
Something like the real forecasts (just to follow HA's standards, below just a mockup):

```
alerts:
  - level: '1'
    type: Zivatar
    icon: mdi:weather-lightning-rainy
  - level: '2'
    type: Hőség
    icon: mdi:weather-sunny-alert
dominant_met_alert_value: 2
dominant_met_alert: Hőség
updated: '2021-06-22T06:00:00+00:00'
nr_of_alerts: '2'
friendly_name: Meteorológiai riasztás
attribution: Data provided by met.hu
forecast:
  - datetime: '2021-06-22T06:00:00+00:00'
    level1: 1
    type1: Zivatar
    icon1: mdi:weather-lightning-rainy
    level2: 2
    type2: Hőség
    icon2: mdi:weather-sunny-alert
    nr_of_alerts: 2
  - datetime: '2021-06-23T06:00:00+00:00'
    level1: 1
    type1: Zivatar
    icon1: mdi:weather-lightning-rainy
    level2: 2
    type2: Hőség
    icon2: mdi:weather-sunny-alert
  - datetime: '2021-06-24T06:00:00+00:00'
    level1: 1
    type1: Zivatar
    icon1: mdi:weather-lightning-rainy
    level2: 2
    type2: Hőség
    icon2: mdi:weather-sunny-alert
  - datetime: '2021-06-25T06:00:00+00:00'
    level1: 1
    type1: Zivatar
    icon1: mdi:weather-lightning-rainy
    level2: 2
    type2: Hőség
    icon2: mdi:weather-sunny-alert
```

So the main part should contain data for 1) (the current/actual state), and under `forecast` you could locate the data for 2) - 5).
